[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "streamlit_id_token_patch"
version = "0.1"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"" = ["patch.pth"]