[project]
name = "st-id-token-patch"
version = "0.1"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.coverage.run]
branch = true
source = "st-id-token-patch"

[tool.hatch.build.hooks.autorun]
dependencies = ["hatch-autorun"]
code = """
import st-id-token-patch
"""